@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.wiccanarts.common.crafting;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;